public: devicetree: remove -Wno-graph_child_address build option
The following error was being observed when building the latest
kernel from linux-next (i.e. tag next-20260122):

FATAL ERROR: Unrecognized check name "graph_child_address"

The following patch merged into upstream dtc and will cause any builds
that use -Wno-graph_child_address to fail with that error.

https://git.kernel.org/pub/scm/utils/dtc/dtc.git/commit/?h=main&id=cba90ce82064ad1e6d25f20d8eaa940bd2fc97ed

Remove this option from our device tree build options.

Bug 5835959

Change-Id: I879c82b0318aa7f1d165e3d2fd8deca9d519ece2
Reviewed-on: https://git-master.nvidia.com/r/c/kernel/build/nvidia-public/+/3534794
(cherry picked from commit 59ab0eaa3807f52edd3e74b5e805f063c91d6d6d)
Reviewed-on: https://git-master.nvidia.com/r/c/kernel/build/nvidia-public/+/3546099
Tested-by: Brad Griffis <bgriffis@nvidia.com>
Reviewed-by: Brad Griffis <bgriffis@nvidia.com>
Reviewed-by: Jon Hunter <jonathanh@nvidia.com>
GVS: buildbot_gerritrpt <buildbot_gerritrpt@nvidia.com>