bmi088: Fix mixed declarations and code
When building the BMI088 driver with the compiler option
'-Werror=declaration-after-statement' the build fails with the following
errors ...

 drivers/bmi088/bmi088_iio.c: In function ‘bmi_iio_attr_store’:
 drivers/bmi088/bmi088_iio.c:226:9: error: ISO C90 forbids mixed
  declarations and code [-Werror=declaration-after-statement]
 226 |         struct bmi_iio_state *st = iio_priv(indio_dev);
     |         ^~~~~~

 drivers/bmi088/bmi088_iio.c: In function ‘bmi_iio_attr_show’:
 drivers/bmi088/bmi088_iio.c:283:9: error: ISO C90 forbids mixed
  declarations and code [-Werror=declaration-after-statement]
 283 |         struct bmi_iio_state *st = iio_priv(indio_dev);
     |         ^~~~~~

Fix this by ensuring that all variables are defined at the start of the
functions.

Bug 4190630

Change-Id: I52e90fbc61d4d33ab8c1dfd4e551a54461aad788
Signed-off-by: Jon Hunter <jonathanh@nvidia.com>
Reviewed-on: https://git-master.nvidia.com/r/c/linux-nv-oot/+/3330356
GVS: buildbot_gerritrpt <buildbot_gerritrpt@nvidia.com>
Reviewed-by: Blake McHale <bmchale@nvidia.com>
Reviewed-by: svcacv <svcacv@nvidia.com>