add set -x to debug ci error
```
/builds/awesome-se/jetson/Linux_for_Tegra/tools/kernel_flash/l4t_initrd_flash_internal.sh --no-flash --external-device nvme0n1p1 -c tools/kernel_flash/flash_l4t_nvme.xml -p -c bootloader/t186ref/cfg/flash_l4t_t194_qspi_p3668.xml --no-systemimg --no-flash --massflash 5 --network usb0 recomputer-xavier-nx-industrial external
 * Stopping NFS kernel daemon
   ...done.
 * Unexporting directories for NFS kernel daemon...
   ...done.
 * Not starting NFS kernel daemon: no exports.
clnt_create: RPC: Unknown host
/builds/awesome-se/jetson/Linux_for_Tegra/rootfs and /builds/awesome-se/jetson/Linux_for_Tegra/tools/kernel_flash are not exported
You can export them by adding entries into /etc/exports
For examples:
/builds/awesome-se/jetson/Linux_for_Tegra/tools/kernel_flash *(rw,nohide,insecure,no_subtree_check,async,no_root_squash)
/builds/awesome-se/jetson/Linux_for_Tegra/rootfs *(rw,nohide,insecure,no_subtree_check,async,no_root_squash)
Note that these entries exposes the folders to requests from any IPs
************************************
*                                  *
*  Step 1: Generate flash packages *
*                                  *
************************************
/builds/awesome-se/jetson/Linux_for_Tegra/tools/kernel_flash/l4t_create_images_for_kernel_flash.sh requires root privilege
Cleaning up...
ERROR: Job failed: exit code 1
```