video: tegra: nvmap: Add missing vmalloc.h
After removing nvmap_priv.h, nvmap no longer builds for Linux v6.10+
kernels and error such as the following are observed ...

 drivers/video/tegra/nvmap/nvmap_alloc.c:41:24: error: implicit
 declaration of function 'vzalloc'; did you mean 'kzalloc'?
 [-Werror=implicit-function-declaration]
   41 |                 return vzalloc(len);
      |                        ^~~~~~~
      |                        kzalloc
 drivers/video/tegra/nvmap/nvmap_alloc.c:52:17:
 error: implicit declaration of function 'vfree'; did you mean
 'kvfree'? [-Werror=implicit-function-declaration]
   52 |                 vfree(ptr);
      |                 ^~~~~
      |                 kvfree

Fix this by including vmalloc.h in the necessary files.

JIRA TMM-5751

Change-Id: I49fae7ea5a78f0029706c2bd12b5553e5903f31b
Signed-off-by: Jon Hunter <jonathanh@nvidia.com>
Reviewed-on: https://git-master.nvidia.com/r/c/linux-nv-oot/+/3243752
GVS: buildbot_gerritrpt <buildbot_gerritrpt@nvidia.com>
Reviewed-by: Ketan Patil <ketanp@nvidia.com>